[package]
name = "export_extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.5"
pathdiff = "0.2.1"