[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-binutils"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[target.x86_64-apple-darwin]
linker = "/opt/homebrew/opt/llvm/bin/clang"
ar = "/opt/homebrew/opt/llvm/bin/llvm-ar"

[target.aarch64-apple-darwin]
linker = "/opt/homebrew/opt/llvm/bin/clang"
ar = "/opt/homebrew/opt/llvm/bin/llvm-ar"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"